// <auto-generated />
using System;
using Daily_Cash_Trading_Limits;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Daily_Cash_Trading_Limits.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201216080523_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Daily_Cash_Trading_Limits.Models.BankName", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BankId");

                    b.ToTable("BankName");
                });

            modelBuilder.Entity("Daily_Cash_Trading_Limits.Models.DailyCalculatedLimit", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Limit")
                        .HasColumnType("INTEGER");

                    b.HasKey("BankId");

                    b.ToTable("DailyCalculatedLimit");
                });

            modelBuilder.Entity("Daily_Cash_Trading_Limits.Models.RiskRating", b =>
                {
                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EffectOnLimit")
                        .HasColumnType("REAL");

                    b.HasKey("Rating");

                    b.ToTable("RiskRating");
                });

            modelBuilder.Entity("Daily_Cash_Trading_Limits.Models.TotalAsset", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Assets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("BankId");

                    b.ToTable("TotalAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
